- name: Configure docker with guest
  hosts: default
  become: True
  tasks:
    - name: install prerequisites
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python-pip']
        state: latest
        update_cache: yes

    - name: install pip packages
      pip:
        name: ['docker-py']
        state: latest

    - name: check if we need to add docker apt key
      shell: "apt-key list | grep 'docker'"
      register: apt_key_added
      ignore_errors: yes

    - name: add docker apt key (alternative for older systems without SNI).
      shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      args:
        warn: false
      when: apt_key_added.stdout == ""

    - name: add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      become: true
      when: apt_key_added.stdout == ""

    - name: install docker
      apt: name=docker-ce update_cache=yes

    - name: add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: create alpine container
      docker_image:
        name: hello-world
        tag: latest
        path: /vagrant/app
        state: present
        force: yes # always rebuild container

    - name: start container
      docker_container:
        name: hello-world
        image: hello-world:latest
        ports: 
          - "80:80"
          - "443:443"
        state: started
        restart: yes